name: 2nd workflow
on:
  push:
    branches: [master]
  workflow_dispatch:
    

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
   
  heroku_build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Maven
      run: mvn -B package
    - name: Upload jar
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
        retention-days: 1
  heroku_publish:
    runs-on: ubuntu-latest
    needs: [heroku_build, tests]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Download Jar
      uses: actions/download-artifact@v1
      with:
        name: target
    - name: Build Docker Image
      run: docker build -t items .
    - name: Install Heroku
      run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Change image name
      run: docker tag items registry.heroku.com/$HEROKU_APP/web
    - name: Login heroku 
      run: heroku container:login
    - name: Push image to Heroku
      run: docker push registry.heroku.com/$HEROKU_APP/web
  heroku_deploy:
    runs-on: ubuntu-latest
    needs: [heroku_publish]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
    - name: Install Heroku
      run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Login heroku
      run: heroku container:login
    - name: Deploy heroku
      run: heroku container:release web
